### ISSUE TITLE
Create a package for pypi

### ISSUE THREAD

**Issue by jugmac00** [perfact/SimpleUserFolder#2]
Hi,

as one of the systems I am responsible for also relies on SimpleUserFolder, and I am about to migrate the system to Zope 4 / Python 3, it would be great if you could create a pip installable package for pypi.

I met @jhinghaus at a Zope sprint last year, and we briefly talked about it.

Best,
Jürgen

**Comment by jhinghaus** [comment]
Hi Jürgen,
I just created a pull request for some changes I'd like to include in the package before the first upload.

**Comment by jugmac00** [comment]
Hi Jens,

meanwhile my app does not use `SimpleUserFolder` any more.

And while it is very convenient to install a package hosted on PyPi, it is also possible to directly install from GitHub, both via `pip` and via `setup.py -> install_requires`.

Thank you very much anyway!
